import {useEffect,useMemo,useRef,useState} from 'react'
import {Copy,Pause,Play,Plus,RotateCcw,Save,SkipBack,SkipForward,Trash2} from 'lucide-react'
import {mutate} from './lib'
import type {StudioObject} from './studio'
import './action-builder.css'

type Position=[number,number]
type SceneItem={id:string;objectId:string;position:Position;rotationAngle:number;label?:string}
type Keyframe={objectId:string;positionX:number;positionY:number;rotationAngle:number;timestamp:number}
export type ActionFields={name:string;description:string;category:string;estimatedDuration:number;tags:string[]}
export type PersistedAction=ActionFields&{id:string;createdAt:string;updatedAt:string;referencedObjects:string[];scene_objects:SceneItem[];keyframes:Keyframe[];previewVideo?:string}
type Props={objects:StudioObject[];palette:StudioObject[];setPalette:(x:StudioObject[])=>void;selected:StudioObject;setSelected:(x:StudioObject)=>void;name:string;setName:(x:string)=>void;loadedAction?:PersistedAction;save:(action:PersistedAction)=>void;notify:(x:string)=>void}
const sceneItem=(objectId:string):SceneItem=>({id:`scene-${objectId}-${Date.now()}`,objectId,position:[0,0],rotationAngle:0})

async function recordActionPreview(scene:SceneItem[],keyframes:Keyframe[],objects:StudioObject[],requestedDuration:number){
 if(typeof MediaRecorder==='undefined')throw new Error('This desktop browser cannot generate Action preview recordings')
 const width=640,height=360,fps=30,duration=Math.max(1,...[requestedDuration,...keyframes.map(frame=>frame.timestamp)].filter(Number.isFinite)),canvas=document.createElement('canvas');canvas.width=width;canvas.height=height
 const context=canvas.getContext('2d');if(!context)throw new Error('Action preview renderer is unavailable')
 const stream=canvas.captureStream(15),mime=MediaRecorder.isTypeSupported('video/webm;codecs=vp8')?'video/webm;codecs=vp8':'video/webm',recorder=new MediaRecorder(stream,{mimeType:mime}),chunks:Blob[]=[]
 recorder.ondataavailable=event=>{if(event.data.size)chunks.push(event.data)}
 const objectMap=new Map(objects.map(item=>[item.id,item]))
 const stateAt=(item:SceneItem,time:number)=>{const frames=keyframes.filter(frame=>frame.objectId===item.objectId).sort((a,b)=>a.timestamp-b.timestamp),before=[...frames].reverse().find(frame=>frame.timestamp<=time),after=frames.find(frame=>frame.timestamp>time);if(!before&&!after)return{position:item.position,rotation:item.rotationAngle};if(!before)return{position:[after!.positionX,after!.positionY] as Position,rotation:after!.rotationAngle};if(!after)return{position:[before.positionX,before.positionY] as Position,rotation:before.rotationAngle};const amount=(time-before.timestamp)/Math.max(.001,after.timestamp-before.timestamp);return{position:[before.positionX+(after.positionX-before.positionX)*amount,before.positionY+(after.positionY-before.positionY)*amount] as Position,rotation:before.rotationAngle+(after.rotationAngle-before.rotationAngle)*amount}}
 const draw=(time:number)=>{context.fillStyle='#0d1117';context.fillRect(0,0,width,height);context.strokeStyle='#263241';for(let x=0;x<=width;x+=40){context.beginPath();context.moveTo(x,0);context.lineTo(x,height);context.stroke()}for(let y=0;y<=height;y+=40){context.beginPath();context.moveTo(0,y);context.lineTo(width,y);context.stroke()}context.fillStyle='#344252';context.fillRect(105,75,430,235);context.strokeStyle='#708198';context.strokeRect(105,75,430,235);for(const item of scene){const object=objectMap.get(item.objectId),state=stateAt(item,time),x=width/2+state.position[0]*64,y=height*.52+state.position[1]*36;context.save();context.translate(x,y);context.rotate(state.rotation*Math.PI/180);context.fillStyle=object?.color||'#4c8dff';context.fillRect(-23,-23,46,46);context.strokeStyle='#e7ebf2';context.lineWidth=2;context.strokeRect(-23,-23,46,46);context.restore();context.fillStyle='#fff';context.font='12px Segoe UI';context.textAlign='center';context.fillText(item.label||object?.name||item.objectId,x,y+39)}context.fillStyle='#d8e2ef';context.font='14px Cascadia Mono';context.textAlign='left';context.fillText(`${time.toFixed(2)}s / ${duration.toFixed(2)}s`,16,28)}
 recorder.start();const started=performance.now();while((performance.now()-started)/1000<duration){draw((performance.now()-started)/1000);await new Promise(resolve=>window.setTimeout(resolve,1000/fps))}draw(duration);recorder.stop();await new Promise<void>((resolve,reject)=>{recorder.onerror=()=>reject(new Error('Action preview recording failed'));recorder.onstop=()=>resolve()})
 stream.getTracks().forEach(track=>track.stop());const blob=new Blob(chunks,{type:'video/webm'});if(!blob.size)throw new Error('Action preview recording was empty');return blob
}

export function ActionBuilder({objects,palette,setPalette,setSelected,name,setName,loadedAction,save,notify}:Props){
 const [scene,setScene]=useState<SceneItem[]>([]),[keyframes,setKeyframes]=useState<Keyframe[]>([]),[selectedId,setSelectedId]=useState<string>(),[time,setTime]=useState(0),[playing,setPlaying]=useState(false),[saving,setSaving]=useState(false),[interaction,setInteraction]=useState<'grab'|'rotate'>(),[snapshot,setSnapshot]=useState<SceneItem>(),[addOpen,setAddOpen]=useState(false),[saveOpen,setSaveOpen]=useState(false),[menu,setMenu]=useState<{x:number;y:number;id:string}>(),[fields,setFields]=useState<ActionFields>({name,description:'',category:'Robot Task',estimatedDuration:5,tags:[]}),loaded=useRef(false),saveTimer=useRef<number|undefined>(undefined),viewport=useRef<HTMLDivElement>(null)
 const objectMap=useMemo(()=>new Map(objects.map(x=>[x.id,x])),[objects]),current=scene.find(x=>x.id===selectedId),ordered=useMemo(()=>[...keyframes].sort((a,b)=>a.timestamp-b.timestamp),[keyframes])
 // Mount-only recovery; subsequent persisted-action changes are handled below.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 useEffect(()=>{if(loadedAction){loaded.current=true;return}fetch('/action-builder/state',{cache:'no-store'}).then(r=>r.ok?r.json():undefined).then(state=>{if(state){setScene((state.scene_objects||[]).map((item:any)=>({...item,position:[Number(item.position?.[0]||0),Number(item.position?.[1]||0)],rotationAngle:Number(item.rotationAngle||0)})));setKeyframes((state.timeline||[]).map((frame:any)=>({objectId:frame.objectId,positionX:Number(frame.positionX||0),positionY:Number(frame.positionY||0),rotationAngle:Number(frame.rotationAngle||0),timestamp:Number(frame.timestamp||0)})));setTime(state.playhead||0)}loaded.current=true}).catch(()=>{loaded.current=true})},[])
 useEffect(()=>{if(!loadedAction)return;setScene(loadedAction.scene_objects||[]);setKeyframes(loadedAction.keyframes||[]);setTime(0);setFields({name:loadedAction.name,description:loadedAction.description,category:loadedAction.category,estimatedDuration:loadedAction.estimatedDuration,tags:loadedAction.tags||[]})},[loadedAction])
 useEffect(()=>{if(!loaded.current)return;window.clearTimeout(saveTimer.current);saveTimer.current=window.setTimeout(()=>void mutate('/action-builder/state','PUT',{scene_objects:scene,timeline:keyframes,playhead:time,snap:true}),250);return()=>window.clearTimeout(saveTimer.current)},[scene,keyframes,time])
 useEffect(()=>{if(!playing)return;const end=Math.max(fields.estimatedDuration,ordered.at(-1)?.timestamp||0,1),timer=window.setInterval(()=>setTime(value=>{if(value>=end){setPlaying(false);return 0}return value+.05}),50);return()=>window.clearInterval(timer)},[playing,fields.estimatedDuration,ordered])
 useEffect(()=>{if(!playing)return;setScene(items=>items.map(item=>{const frame=[...ordered].reverse().find(x=>x.objectId===item.objectId&&x.timestamp<=time);return frame?{...item,position:[frame.positionX,frame.positionY],rotationAngle:frame.rotationAngle}:item}))},[playing,time,ordered])
 const select=(item:SceneItem)=>{setSelectedId(item.id);const object=objectMap.get(item.objectId);if(object)setSelected(object)}
 const add=(object:StudioObject)=>{const item=sceneItem(object.id);setScene(xs=>[...xs,item]);setPalette([...palette.filter(x=>x.id!==object.id),object]);select(item);setAddOpen(false)}
 const remove=(id=selectedId)=>{if(!id)return;const item=scene.find(x=>x.id===id);setScene(xs=>xs.filter(x=>x.id!==id));setKeyframes(xs=>xs.filter(x=>x.objectId!==item?.objectId));if(id===selectedId)setSelectedId(undefined)}
 const duplicate=(id:string)=>{const item=scene.find(x=>x.id===id);if(!item)return;const copy={...item,id:`scene-${item.objectId}-${Date.now()}`,position:[item.position[0]+.3,item.position[1]] as Position};setScene(xs=>[...xs,copy]);select(copy);setMenu(undefined)}
 const rename=(id:string)=>{const item=scene.find(x=>x.id===id),object=item&&objectMap.get(item.objectId);if(!item||!object)return;const value=prompt('Object label',item.label||object.name);if(value){setScene(xs=>xs.map(x=>x.id===id?{...x,label:value}:x));notify(`Scene label changed to ${value}`)}setMenu(undefined)}
 const reset=()=>{setScene([]);setKeyframes([]);setTime(0);setPlaying(false);setInteraction(undefined);setSelectedId(undefined);setPalette([]);notify('Action Builder reset')}
 const begin=(kind:'grab'|'rotate')=>{if(!current)return;setSnapshot({...current,position:[...current.position] as Position});setInteraction(kind);viewport.current?.focus()}
 const cancel=()=>{if(snapshot)setScene(xs=>xs.map(x=>x.id===snapshot.id?snapshot:x));setInteraction(undefined);setSnapshot(undefined)}
 const place=()=>{setInteraction(undefined);setSnapshot(undefined)}
 const move=(e:React.PointerEvent)=>{if(!current||interaction!=='grab')return;const bounds=viewport.current?.getBoundingClientRect();if(!bounds)return;const x=(e.clientX-bounds.left)/bounds.width*6-3,y=(e.clientY-bounds.top)/bounds.height*4-2;setScene(xs=>xs.map(item=>item.id===current.id?{...item,position:[x,y]}:item))}
 const rotate=(e:React.WheelEvent)=>{if(!current||interaction!=='rotate')return;e.preventDefault();const amount=e.deltaY<0?15:-15;setScene(xs=>xs.map(item=>item.id===current.id?{...item,rotationAngle:(item.rotationAngle+amount)%360}:item))}
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.target as HTMLElement).matches('input,textarea'))return;if(e.key.toLowerCase()==='g')begin('grab');if(e.key.toLowerCase()==='r')begin('rotate');if(e.key==='Escape')cancel()};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)})
 const addKeyframe=()=>{if(!current){notify('Select an object first');return}const frame={objectId:current.objectId,positionX:current.position[0],positionY:current.position[1],rotationAngle:current.rotationAngle,timestamp:Number(time.toFixed(2))};setKeyframes(xs=>[...xs.filter(x=>!(x.objectId===frame.objectId&&x.timestamp===frame.timestamp)),frame]);notify(`Keyframe added at ${frame.timestamp.toFixed(2)}s`)}
 const applyFrame=(frame?:Keyframe)=>{if(!frame)return;setTime(frame.timestamp);setScene(xs=>xs.map(x=>x.objectId===frame.objectId?{...x,position:[frame.positionX,frame.positionY],rotationAngle:frame.rotationAngle}:x));const item=scene.find(x=>x.objectId===frame.objectId);if(item)select(item)}
 const previous=()=>applyFrame([...ordered].reverse().find(x=>x.timestamp<time-.001)||ordered[0]),next=()=>applyFrame(ordered.find(x=>x.timestamp>time+.001)||ordered.at(-1))
 const submit=async()=>{if(!fields.name.trim()){notify('Action name is required');return}setSaving(true);try{notify('Rendering Action preview…');const preview=await recordActionPreview(scene,keyframes,objects,fields.estimatedDuration),metadata=new TextEncoder().encode(JSON.stringify({...fields,scene_objects:scene,keyframes})),header=new Uint8Array(4);new DataView(header.buffer).setUint32(0,metadata.length);const response=await fetch('/actions',{method:'POST',headers:{'Content-Type':'application/vnd.taskgraph.action+webm'},body:new Blob([header,metadata,preview])});if(!response.ok)throw new Error(await response.text());const result=await response.json() as {action:PersistedAction};save(result.action);setName(result.action.name);setSaveOpen(false);notify(`${result.action.name} saved to Action Library`)}catch(reason){const message=reason instanceof Error?reason.message:'Unable to save action';notify(message);window.alert(`Save Action failed\n\nStage: Preview generation or persistence\nReason: ${message}\nSuggested action: Try Save Action again.`)}finally{setSaving(false)}}
 return <div className="builder teaching-builder"><div className="builder-toolbar"><div><button disabled={saving} onClick={()=>setSaveOpen(true)}><Save/> {saving?'Rendering Preview…':'Save Action'}</button><button onClick={reset}><RotateCcw/> Reset</button></div><small>Keyboard: G Grab · R Rotate X · Click Confirm · Esc Cancel</small></div><div className="teaching-layout">
  <section className="studio-panel teaching-palette"><header><span>Object Palette</span><small>{scene.length} objects</small></header><div>{scene.map(item=>{const object=objectMap.get(item.objectId);if(!object)return null;return <button key={item.id} className={selectedId===item.id?'selected':''} onClick={()=>select(item)} onDoubleClick={()=>remove(item.id)} onContextMenu={e=>{e.preventDefault();setMenu({x:e.clientX,y:e.clientY,id:item.id})}}><span>{object.image?<img src={object.image}/>:null}</span><b>{item.label||object.name}</b></button>})}</div><button className="add-library-object" onClick={()=>setAddOpen(true)}><Plus/> Add Object</button></section>
  <section className="studio-panel teaching-viewport"><header><span>2D Teaching Workspace</span><small>{interaction==='grab'?'GRAB — move on tabletop and click to place':interaction==='rotate'?'ROTATE — scroll in 15° increments and click to confirm':'FIXED TOP-DOWN TABLETOP'}</small></header><div ref={viewport} tabIndex={0} className={`simple-viewport ${interaction||''}`} onPointerMove={move} onWheel={rotate} onClick={interaction?place:undefined}><div className="simple-table"/>{scene.map(item=>{const object=objectMap.get(item.objectId);if(!object)return null;return <button key={item.id} className={`thumbnail-plane ${selectedId===item.id?'selected':''}`} onClick={e=>{if(interaction)return;e.stopPropagation();select(item)}} style={{left:`${50+item.position[0]*10}%`,top:`${52+item.position[1]*10}%`,transform:`translate(-50%,-50%) rotate(${item.rotationAngle}deg)`}}>{object.image?<img src={object.image} alt={object.name}/>:null}<em>{item.label||object.name}</em></button>})}</div></section>
  <section className="studio-panel simple-timeline"><header><span>Object State Timeline</span><small>{keyframes.length} keyframes</small></header><div className="simple-timeline-controls"><button onClick={previous} title="Previous keyframe"><SkipBack/></button><button onClick={()=>setPlaying(!playing)} title={playing?'Pause':'Play'}>{playing?<Pause/>:<Play/>}</button><button onClick={next} title="Next keyframe"><SkipForward/></button><button onClick={addKeyframe}><Plus/> Keyframe</button><span>{time.toFixed(2)}s</span></div><div className="keyframe-track">{ordered.map(frame=><button key={`${frame.objectId}-${frame.timestamp}`} className={Math.abs(frame.timestamp-time)<.01?'active':''} style={{left:`${Math.min(100,frame.timestamp/Math.max(fields.estimatedDuration,1)*100)}%`}} onClick={()=>applyFrame(frame)} title={`${objectMap.get(frame.objectId)?.name} · ${frame.timestamp}s`}><i/><span>{frame.timestamp.toFixed(1)}s</span></button>)}<em style={{left:`${Math.min(100,time/Math.max(fields.estimatedDuration,1)*100)}%`}}/></div></section>
 </div>{menu&&<div className="palette-menu" style={{left:menu.x,top:menu.y}} onMouseLeave={()=>setMenu(undefined)}><button onClick={()=>remove(menu.id)}><Trash2/> Delete</button><button onClick={()=>duplicate(menu.id)}><Copy/> Duplicate</button><button onClick={()=>rename(menu.id)}>Rename</button></div>}{addOpen&&<div className="teaching-modal" onMouseDown={()=>setAddOpen(false)}><div onMouseDown={e=>e.stopPropagation()}><h2>Add from Object Library</h2>{objects.map(object=><button className="library-choice" onClick={()=>add(object)} key={object.id}><span>{object.image?<img src={object.image}/>:null}</span><b>{object.name}</b><small>{object.category}</small></button>)}<button onClick={()=>setAddOpen(false)}>Cancel</button></div></div>}{saveOpen&&<div className="teaching-modal" onMouseDown={()=>setSaveOpen(false)}><div className="save-action-dialog" onMouseDown={e=>e.stopPropagation()}><h2>Save Action</h2><label>Action Name<input value={fields.name} onChange={e=>setFields({...fields,name:e.target.value})}/></label><label>Description<textarea value={fields.description} onChange={e=>setFields({...fields,description:e.target.value})}/></label><label>Category<input value={fields.category} onChange={e=>setFields({...fields,category:e.target.value})}/></label><label>Estimated Duration<input type="number" min="0" step=".1" value={fields.estimatedDuration} onChange={e=>setFields({...fields,estimatedDuration:Number(e.target.value)})}/></label><label>Tags<input value={fields.tags.join(', ')} onChange={e=>setFields({...fields,tags:e.target.value.split(',').map(x=>x.trim()).filter(Boolean)})}/></label><footer><button onClick={()=>setSaveOpen(false)}>Cancel</button><button className="primary" onClick={submit}>Save Action</button></footer></div></div>}</div>
}
