import {motion} from 'framer-motion'
import {Activity,BookOpen,Boxes,Brain,ChevronLeft,ChevronRight,Cpu,FolderOpen,GalleryHorizontalEnd,GitBranch,Hand,Menu,Upload,Waypoints,Zap} from 'lucide-react'
import type {AppData,Runtime} from './lib'
export const navigation=[['Import Video',Upload],['Frame Gallery',GalleryHorizontalEnd],['Detected Objects',FolderOpen],['Object Library',Boxes],['Semantic Inventory',BookOpen],['Knowledge Viewer',Brain],['Affordance Viewer',Hand],['Planner Viewer',Waypoints],['TaskIR Viewer',GitBranch],['Explainability',Brain],['Scene Builder',Waypoints]] as const
export function Badge({children,tone='blue'}:{children:any;tone?:string}){return <span className={`badge ${tone}`}>{children}</span>}
export function Button({children,kind='',...p}:React.ButtonHTMLAttributes<HTMLButtonElement>&{kind?:string}){return <button className={`button ${kind}`} {...p}>{children}</button>}
export function Page({title,subtitle,action,children}:{title:string;subtitle:string;action?:any;children:any}){return <main className="page"><header className="page-head"><div><small>TaskGraph workstation</small><h1>{title}</h1><p>{subtitle}</p></div>{action}</header>{children}</main>}
export function Panel({title,kicker,action,children,className=''}:{title:string;kicker?:string;action?:any;children:any;className?:string}){return <section className={`panel ${className}`}><header><div>{kicker&&<small>{kicker}</small>}<h2>{title}</h2></div>{action}</header>{children}</section>}
export function Empty({icon:Icon,title,text}:{icon:any;title:string;text:string}){return <div className="empty"><Icon/><h3>{title}</h3><p>{text}</p></div>}
export function Progress({value}:{value:number}){return <div className="progress"><i style={{width:`${Math.min(100,value)}%`}}/></div>}
export function Topbar({onMenu,runtime}:{onMenu:()=>void;runtime?:Runtime}){return <header className="topbar"><button className="menu" onClick={onMenu}><Menu/></button><div className="brand"><span><GitBranch/></span><div><b>TaskGraph</b><small>Robotic Teaching Workstation</small></div></div><div className="top-meta"><Badge>v1.1.2</Badge><span><Cpu/> {runtime?.accelerator.gpu_name||'Compute device'}</span><span><Zap/> {runtime?.accelerator.cuda_available?'CUDA ready':'CPU mode'}</span></div></header>}
export function Sidebar({active,collapsed,open,onNavigate,onCollapse}:{active:string;collapsed:boolean;open:boolean;onNavigate:(x:string)=>void;onCollapse:()=>void}){return <aside className={`sidebar ${open?'open':''}`}>{navigation.map(([name,Icon],i)=><motion.button initial={{opacity:0,x:-8}} animate={{opacity:1,x:0}} transition={{delay:i*.025}} className={active===name?'active':''} onClick={()=>onNavigate(name)} title={name} key={name}><Icon/><span>{name}</span></motion.button>)}<button className="collapse" onClick={onCollapse}>{collapsed?<ChevronRight/>:<ChevronLeft/>}<span>Collapse</span></button></aside>}
export function StatusBar({data}:{data:AppData}){const r=data.runtime,d=data.detections?.detections?.length||0,o=data.objects?.objects?.length||0;return <footer><span><Activity/>Task <b>{r?.workspace.processed?'Cluster review':'Ready'}</b></span><span>Frame <b>{r?.workspace.processed||0}/{r?.workspace.frames||0}</b></span><span>Detection <b>{d}</b></span><span>Review <b>{o}/{d}</b></span><span><Cpu/>GPU <b>{r?.accelerator.gpu_name||'CPU'}</b></span><span>Memory <b>{((r?.metrics.ram_bytes||0)/1e9).toFixed(1)} GB</b></span><span>Worker <b>Healthy</b></span><span>FPS <b>{Number(r?.metrics.inference_fps||0).toFixed(1)}</b></span><span>Queue <b>{r?.workers.queue_size||0}</b></span><span>ETA <b>—</b></span><span>Scene <b>{data.scene?.objects?.length||0}n/{data.scene?.relationships?.length||0}e</b></span><span>Objects <b>{o}</b></span></footer>}
