{
  "version": 1,
  "id": "action-0407ea97747c",
  "name": "pick spoon",
  "description": "",
  "category": "Robot Task",
  "estimatedDuration": 5.0,
  "previewVideo": "/action-assets/action-0407ea97747c/preview.webm",
  "tags": [],
  "createdAt": "2026-07-22T14:59:18",
  "updatedAt": "2026-07-22T14:59:18",
  "referencedObjects": [
    "user-object-32468f735f2d"
  ],
  "scene_objects": [
    {
      "id": "scene-user-object-32468f735f2d-1784698429212",
      "objectId": "user-object-32468f735f2d",
      "position": [
        2.5092621540972333,
        1.3872975051405776
      ],
      "rotationAngle": 0.0
    }
  ],
  "keyframes": [
    {
      "timestamp": 0.2,
      "objectId": "user-object-32468f735f2d",
      "positionX": -2.8217406539252314,
      "positionY": 1.4337901278742216,
      "rotationAngle": 0.0
    },
    {
      "timestamp": 0.4,
      "objectId": "user-object-32468f735f2d",
      "positionX": -1.7689618316946536,
      "positionY": 1.4470734448118,
      "rotationAngle": 0.0
    },
    {
      "timestamp": 0.7,
      "objectId": "user-object-32468f735f2d",
      "positionX": -0.8210416083328669,
      "positionY": 1.4869239023505947,
      "rotationAngle": 105.0
    },
    {
      "timestamp": 1.3,
      "objectId": "user-object-32468f735f2d",
      "positionX": -0.8210416083328669,
      "positionY": 1.4869239023505947,
      "rotationAngle": 105.0
    },
    {
      "timestamp": 1.75,
      "objectId": "user-object-32468f735f2d",
      "positionX": -0.4393569548556391,
      "positionY": -1.9867164296993918,
      "rotationAngle": 105.0
    },
    {
      "timestamp": 2.35,
      "objectId": "user-object-32468f735f2d",
      "positionX": 1.5571476571812575,
      "positionY": -2.0,
      "rotationAngle": 105.0
    },
    {
      "timestamp": 3.15,
      "objectId": "user-object-32468f735f2d",
      "positionX": 2.5092621540972333,
      "positionY": 1.3872975051405776,
      "rotationAngle": 105.0
    },
    {
      "timestamp": 3.7,
      "objectId": "user-object-32468f735f2d",
      "positionX": 2.5092621540972333,
      "positionY": 1.3872975051405776,
      "rotationAngle": 0.0
    }
  ]
}